Arduino/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('webapp/',include('webapp.urls')),
    path('useraccounts/', include('useraccounts.urls')),
    path('mpesapay/',include('mpesapay.urls')),
]

mpesapay/urls.py
from django.urls import path
from .views import *

app_name='mpesapay'

urlpatterns=[
    path('mpesapay/', Mpesapay.as_view(), name='mpesa'),
]

useraccounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='useraccounts'

urlpatterns=[
    path('register/', views.Registerview, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),   
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path
from . import views

app_name='webapp'

urlpatterns=[
    path('home/', views.index, name='home'), 
    path('excelData', views.excelData, name='excelData'),
    
]

mpesapay/models.py
from django.db import models

# Create your models here.

webapp/models.py
from django.db import models

# Create your models here.

class Streamer(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    operator=models.CharField(max_length=20)
    data_stream=models.FloatField()
    class Meta:
        ordering = ['-timestamp']
    

    def __str__(self):
        return self.operator

mpesapay/forms.py
from django import forms


class Mpesadata(forms.Form):
    name= forms.CharField(label='name', max_length=20)
    id_number= forms.IntegerField(label='id_number')
    description = forms.CharField(label='description',widget=forms.Textarea)
    #implement the means as choices 
    #predefine choices 
    payment_choices=[
        ('', '--select--'),
        ('D', 'direct deposit'),
        ('T', 'till number'),
        ('P', 'paybill'),
        ('PO', 'pochi la biashara')
    ]
    means=forms.ChoiceField(
        choices=payment_choices,
        widget=forms.Select(attrs={'class': 'form-control'}),  
        label='Select Payment method'
    )

useraccounts/forms.py
from django.contrib.auth.models import User
from django import forms

class RegistrationForm(forms.ModelForm):
    password1=forms.CharField(label='password', widget=forms.PasswordInput)
    password2=forms.CharField(label='Confirm password', widget=forms.PasswordInput)
    profile=forms.ImageField(label='Select an image', widget=forms.ClearableFileInput(attrs={'accept': 'image/*'}))
    #model other parameters from the User method
    class Meta:
        model=User
        fields=['first_name', 'last_name', 'username','email']

    def validator(self):
        #the super method is valid only within a class it is used to call the validator method
        cleaned_data=super().validator()
        password1=self.cleaned_data.get("password1")
        password2=self.cleaned_data.get("password2")

        #validation 
        if (password1 == password2):
            raise forms.ValidationError("Passwords do not match")    
        return password1
    

mpesapay/views.py
from django.shortcuts import render
from django.views import View
from .forms import Mpesadata
from django_daraja.mpesa.core import MpesaClient

# Create your views here.

class Mpesapay(View):
    formClass=Mpesadata
    template_name="mpesapay/lipanampesa.html"
    initial={'keny':'value'}
    def get(self,request):
        form=self.formClass(initial=self.initial)
        return render(request, self.template_name,{'form':form})
    
    def post(self,request):
        form=self.formClass(request.POST)
        if form.is_valid():
            #Access the varius variables passed in the form to process payments 
            name= request.POST['name']
            id_number= request.POST['id_number']
            means= request.POST['means']
            description= request.POST['description']
            #Switch the means so as to process payments based on user selection
            match means:
                case "Direct deposit":
                    pass
                case "Pay bill":
                    pass
                case "Till number":
                    pass
                case "Pochi":
                    pass
        return render(request, self.template_name,{'form':form})

useraccounts/views.py
from django.shortcuts import render,redirect
from .forms import *
from django.contrib import messages
from django.contrib.auth.models import auth
from django.contrib.auth import authenticate,login
from django.http import HttpResponse
from django.core.mail import send_mail
from django.conf import settings
from datetime import datetime
import pytz
# Create your views here.
# User registration view
def Registerview(request):
    if (request.method=='POST'):
        user_form=RegistrationForm(request.POST,request.FILES)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(user_form.cleaned_data['password1'])
            # Save the User object
            new_user.save()
            messages.success(request, "Registration successful!!")
            return redirect("useraccounts:login")
    else:
        user_form=RegistrationForm()
    return render(request,'useraccounts/register.html', {'user_form':user_form})

#User login 
def login(request):
    if (request.method=='POST'):
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=auth.authenticate(username=username, password=password)

        if user is not None:          
            auth.login(request,user)
            format="%Y-%m-%d %H:%M:%S %Z"
            time =datetime.now(pytz.timezone('Africa/Nairobi'))
            login_time=time.strftime(format)
            send_mail(
                subject='User log',
                message= f" {username} logged in today at: {login_time} \n Session stream : \n ",
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=["sotieno679@gmail.com"]
                )
            return render(request, 'webapp/index.html')
    else:
        return render(request, 'useraccounts/login.html')

#User logout 
def logout(request):
    auth.logout(request)
    return HttpResponse('Logged out Bye!')

webapp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from . models import *
import serial
from django.http import HttpResponse
import xlwt
from datetime import datetime
from .models import Streamer
from drawnow import *
import matplotlib.pyplot as plt


# Create your views here.
@login_required
def index(request):
    # if (request.method=='POST'):
    #     arduino_data= serial.Serial('com5',9600)
    #     while(True):
    #         if(arduino_data.in_waiting > 0):
    #             raw_data=arduino_data.readline()
    #             global samples
    #             samples=float(raw_data)
    #             print(samples)
    #             #save the data samples and the name of the person streaming the data
    #             streamed_data=Streamer(data_stream=samples,operator=request.user)
    #             streamed_data.save()   

    # render the data for display
    data=Streamer.objects.all()
    ''' dataplot=float(data)

    #plot the data
    def plotter():
        plt.plot(dataplot)
        plt.ylabel('Data')
        plt.title("Sensor data")
    drawnow(plotter)
    pause(0.001) '''
    return render(request, 'webapp/index.html',{'data':data})

# Export the data into ana excel spreadsheet
def excelData(request):
    response=HttpResponse(content_type='application/ms-excel')
    # create content disposition and name the file
    response['Content-Disposition']='attachment; filename=data' + str(datetime.now())+ '.xls'
    # create a workbook 
    wb=xlwt.Workbook(encoding='utf-8')
    #create a worksheet
    ws=wb.add_sheet('Sensor data')
    # add row numbers (variable)
    row_num=0
    # add styling for the labels
    font_style=xlwt.XFStyle()
    font_style.font.bold=True # Set font size to bold

    #column labels
    columns=['Date','Sensor_value', 'Operator']

    # append the data into the columns and rows
    for colmn_num in range(len(columns)):
        ws.write(row_num, colmn_num,columns[colmn_num],font_style)

    # reset font style so that only the headers keep it
    font_style=xlwt.XFStyle()

    #create dynamic rows 
    rows=Streamer.objects.filter(operator=request.user).values_list('timestamp','data_stream', 'operator')
    for row in rows:
        row_num+=1

        for colmn_num in range(len(row)):
            ws.write(row_num, colmn_num, str(row[colmn_num]),font_style)
    #add worksheet to workbook
    wb.save(response)
    return response

mpesapay/templates/mpesapay/lipanampesa.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>lipa</title>
</head>
<body>
    <h3><center><b>PAY HERE!!</b></center></h3>
    <br>
    <a href="{% url 'useraccounts:logout' %}">Logout</a>
    <a href="{% url 'webapp:home' %}">Home</a>
        <form action="{% url 'webapp:home' %}" method="post"><br>
    <form action="{% url 'mpesapay:mpesa' %}" method="post">
        {% csrf_token %}
        {{form.as_p}}

        <input type="submit" value="Submit">
    </form>
</body>
</html>

useraccounts/templates/useraccounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>login</title>
</head>
<body>
    <p><center><b>LOGIN!!</b></center></p>
    {% if messages %}
        {% for message in messages %}
        <div style="color:red;">
            {{message}}
        </div>     
        {% endfor %}
    {% endif %} <br>
    <a href="{% url 'useraccounts:logout' %}">Logout</a>
    <a href="{% url 'webapp:home' %}">Home</a>
    <a href="{% url 'useraccounts:register' %}">sign-up</a>
    {% block content %}
    <form action="{% url 'useraccounts:login' %}" method="post">  
        {% csrf_token %}   
        <input type="text" name="username" id="" placeholder="username"><br><br>
        <input type="password" name="password" id="" placeholder="password"><br><br>
        <input type="submit" value="Login">
    </form>
    {% endblock content %}
</body>
</html>

useraccounts/templates/useraccounts/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>register</title>
</head>
<body>
    <p><center><b>REGISTER!!</b></center></p>
    <a href="{% url 'useraccounts:login' %}">Login</a>
    <a href="{% url 'webapp:home' %}">Home</a>
    {% block content %}
    <form action="{% url 'useraccounts:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        <input type="submit" value="sign-up">
    </form>
    {% endblock content %}
</body>
</html>

webapp/templates/webapp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>home</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    
</head>
<body>
    <p><center><b>HOME!!</b></center></p>
    {% if user.is_authenticated %}
        <p>Hello {{ user.first_name }}</p> <br>
        <a href="{% url 'useraccounts:logout' %}">Logout</a>
        <a href="{% url 'mpesapay:mpesa' %}">Pay for stream</a>
        <form action="{% url 'webapp:home' %}" method="post"><br>
            {% csrf_token %}
            <input type="submit" value="START STREAM"><br>
        </form>
        <a href="{% url 'webapp:excelData' %}"> export to excel </a>
    {% endif %}

    <h4>Session Stream: </h4><br>
    <button id="bang"> show data </button>
        <div class="hidden" id="show_data">
            <table>
                <tr>
                    <th>Data</th>
                    <th>Time Stamp</th>
                </tr>
                {% for data in data %}
                <tr>           
                    <td>{{data.data_stream}}</td>  
                    <td>{{data.timestamp}}</td>     
                </tr>
                {% endfor %}
            </table>
        </div>

            
        <script src="{% static 'JS/mAin.js' %}"></script>

</body>
</html>